services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=khazip
      - POSTGRES_PASSWORD=12345
    networks:
      - stats-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U khazip -d stats"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - stats-db-data:/var/lib/postgresql/data

  stats-server:
    build:
      context: ./statistics/statistics-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=khazip
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_INITIALIZATION_MODE=never
    networks:
      - stats-network

  ewm-service:
    build: ./main
    image: main-image
    container_name: main-container
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - CLIENT_URL=http://stats-server:9090
    networks:
      - stats-network
    depends_on:
      stats-server:
        condition: service_healthy

networks:
  stats-network:
    driver: bridge

volumes:
  stats-db-data:
