version: '3.9'

services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=khazip
      - POSTGRES_PASSWORD=12345
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U khazip"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-server:
    build:
      context: ./statistics/statistics-server
    image: stats-server-image
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=khazip
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_LIQUIBASE_ENABLED=false
    ports:
      - "9090:9090"

volumes:
  stats-db-data:
