services:
  stats-server:
    build:
      context: ./statistics/statistics-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=khazip
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      - stats-network

  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=khazip
      - POSTGRES_PASSWORD=12345
    networks:
      - stats-network

  ewm-service:
    image: busybox
    container_name: main-container
    command: sh -c "echo 'ewm-service is disabled'; sleep infinity"
    networks:
      - stats-network

networks:
  stats-network:
    driver: bridge
