services:
  stats-server:
    build:
      context: ./statistics/statistics-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=khazip
      - SPRING_DATASOURCE_PASSWORD=12345
    networks:
      - stats-network

  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=khazip
      - POSTGRES_PASSWORD=12345
    networks:
      - stats-network

  ewm-service:
    build: ./main
    image: main-image
    container_name: main-container
    ports:
      - "8080:8080"
    depends_on:
      stats-server:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - CLIENT_URL=http://stats-server:9090
    networks:
      - stats-network

networks:
  stats-network:
    driver: bridge