services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=khazip
      - POSTGRES_PASSWORD=12345
    networks:
      - stats-network
    healthcheck:
      test: pg_isready -q -d stats -U khazip
      interval: 10s
      timeout: 5s
      retries: 5

  stats-server:
    build:
      context: statistics/statistics-server
      dockerfile: Dockerfile
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=khazip
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_INITIALIZATION_MODE=never
    networks:
      - stats-network

  ewm-service:
    build:
      context: main
      dockerfile: Dockerfile
    image: main-image
    container_name: main-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - STATS_SERVER_URL=http://stats-server:9090
    networks:
      - stats-network
    depends_on:
      - ewm-db
      - stats-server

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm-db
    healthcheck:
      test: pg_isready -q -d ewm-db -U ewm
      timeout: 5s
      interval: 5s
      retries: 10

networks:
  stats-network:
    driver: bridge